Prototype
icatalin201/product-tracker pull request #2
Opened 2020-10-26 10:21 UTC by AsuSoftware

Am rezolvat problemele. Astept code review

2020-10-26 20:56 UTC, icatalin201 requested changes

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/exceptions/NotFoundCountryException.java
> +public class NotFoundCountryException extends RuntimeException {
merge mai bine CountryNotFoundException

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/exceptions/NotFoundCountyException.java
> +public class NotFoundCountyException extends RuntimeException {
la fel si aici

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/handlerExceptions/ApiException.java
> +    private final HttpStatus httpStatus;
aici care e scopul statusului http si al timestamp? 
cu ce scop le-ai adaugat?

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/handlerExceptions/ApiException.java
> +public class ApiException {
ce face clasa asta?
ca nu extinde nicio alta Exceptie, si nici nu e folosita in alta parte

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/handlerExceptions/CountyExceptionHandler.java
> +public class CountyExceptionHandler {
nu avem nevoie de handler momentan

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/UserService.java
> +    private UserCreatorImpl userCreator;
SOLID principles.
D vine de la Dependency inversion principle care spune sa setam dependinte abstracte, nu concrete. In alte cuvinte nu implementari, ci interfete.
ex `private UserCreator userCreator`

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/address/AddressFinderImpl.java
> +        ids.forEach(id -> countryList.add(countryRepository.findById(id).orElseThrow(NotFoundCountryException::new)));
nu vad de ce ai facut asa ceva... in repo exista deja metoda `findAllById(Iterable<T> ids)`... care intoarce fix ce ai tu nevoie

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/address/AddressFinderImpl.java
> +        ids.forEach(id -> countyList.add(countyRepository.findById(id).orElseThrow(NotFoundCountyException::new)));
la fel ca mai sus

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/address/addressInterface/AddressFinder.java
> +  List<Country> findCountriesById(Iterable<UUID> ids);
da-i revert, folosim cel mai abstract tip de colectie

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/user/UserCreatorImpl.java
> +        County county = countyRepository.findById(createUserDto.getCountyId()).orElseThrow(NotFoundCountyException::new);
de ce mai ai AddressFinder daca tu folosesti repository-ul?

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/user/userInterface/UserDelete.java
> +public interface UserDelete {
UserDelete, UserRetrieve, UserUpdate... n-au niciun sens ca denumire plus ca-s puse aiurea, sterge-le

2020-10-26 20:56 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/user/userInterface/UserDelete.java
> +public interface UserDelete {
la fel si implementarile lor

2020-10-27 08:33 UTC, AsuSoftware commented on src/main/java/com/app/ca/product/tracker/handlerExceptions/ApiException.java
> +    private final HttpStatus httpStatus;
Lam pus ca sa se vada statusul la response si la ce ora. Am avut asa si la ecommerce

2020-10-27 08:33 UTC, AsuSoftware commented on src/main/java/com/app/ca/product/tracker/handlerExceptions/ApiException.java
> +public class ApiException {
Pai nu am implemantato inca, ai zis ca trebuie stearsa

2020-10-27 08:33 UTC, AsuSoftware commented on src/main/java/com/app/ca/product/tracker/handlerExceptions/CountyExceptionHandler.java
> +public class CountyExceptionHandler {
ok

2020-10-27 08:39 UTC, AsuSoftware commented on src/main/java/com/app/ca/product/tracker/service/address/addressInterface/AddressFinder.java
> +  List<Country> findCountriesById(Iterable<UUID> ids);
in ce sens revert? Ele sunt deja List<Country> findCountriesById(Iterable<UUID> ids); Il am asa

2020-10-27 08:48 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/handlerExceptions/ApiException.java
> +    private final HttpStatus httpStatus;
pai si foloseste la ceva momentan? plus ca nu era in scopul taskului :))

2020-10-27 08:50 UTC, icatalin201 commented on src/main/java/com/app/ca/product/tracker/service/address/addressInterface/AddressFinder.java
> +  List<Country> findCountriesById(Iterable<UUID> ids);
revert la ce ai modificat, returna Iterable si ai pus tu sa returneze List. De ce?

2020-10-27 09:45 UTC, closed without merging